package com.davedaniels.j8ia;

import com.davedaniels.j8ia.model.Apple;

import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {

    public Main() {

    }

    public void appleSort(List<Apple> inventory) {
        inventory.sort((Apple o1, Apple o2) -> o1.getWeight() - o2.getWeight());
    }
}
